'use server'

import { revalidatePath } from 'next/cache'
import { z } from 'zod'
import { createServerSupabase } from '@/lib/supabase/server'
import { isoDate, money, parseRecords, value } from '@/lib/import/csv-parse'

export type ImportResult =
  | {
      ok: true
      /** Lines that found an account and became cash transactions. */
      matched: number
      /** Lines held for review because no account could be placed. */
      unmatched: number
      /** Lines the file itself could not answer for: no date, or no amount. */
      unreadable: number
    }
  | { ok: false; message: string }

const inputSchema = z.object({
  fileName: z.string().max(200),
  period: z.string().max(40).optional(),
  csv: z.string().min(1, 'that file is empty').max(8_000_000),
})

/** The columns the importer needs. Everything else in the export is ignored. */
const REQUIRED = ['Date', 'Account Number', 'Amount']

/**
 * Imports a Rocket statement.
 *
 * The inversion — a negative Amount is money in — belongs to `import_bank_line`
 * and stays there. Reading the file must not quietly do it first, or the two
 * would fight and the sign would depend on which ran last.
 *
 * A line whose account cannot be placed is not dropped: the database holds it
 * in a review queue, because a bank line nobody can place is exactly the thing
 * that ends up explaining a reconciliation difference three weeks later.
 */
export async function importBankStatement(input: unknown): Promise<ImportResult> {
  const parsed = inputSchema.safeParse(input)
  if (!parsed.success) {
    return { ok: false, message: parsed.error.issues[0]?.message ?? 'Invalid file' }
  }

  const { headers, rows } = parseRecords(parsed.data.csv)
  if (rows.length === 0) return { ok: false, message: 'that file has no rows in it' }

  const have = new Set(headers.map((h) => h.toLowerCase()))
  const missing = REQUIRED.filter((h) => !have.has(h.toLowerCase()))
  if (missing.length > 0) {
    // Naming them beats "invalid format": the usual cause is somebody exporting
    // the working sheet rather than the statement.
    return {
      ok: false,
      message: `this file has no ${missing.join(', ')} column — export the statement itself, not the working sheet`,
    }
  }

  const supabase = await createServerSupabase()
  const { data: batch, error: batchError } = await supabase
    .from('bank_import_batch')
    .insert({ file_name: parsed.data.fileName, statement_period: parsed.data.period ?? null })
    .select('id')
    .single()
  if (batchError) return { ok: false, message: batchError.message }

  let matched = 0
  let unmatched = 0
  let unreadable = 0

  for (const row of rows) {
    const date = isoDate(value(row, 'Date'))
    const amount = money(value(row, 'Amount'))
    // A row with no date or no amount is not a transaction, and guessing either
    // would put a real figure on a made-up day.
    if (date === null || amount === null) { unreadable += 1; continue }

    const { data, error } = await supabase.rpc('import_bank_line', {
      p_batch_id: batch.id,
      p_account_no: value(row, 'Account Number') || null,
      p_account_name: value(row, 'Account Name') || null,
      p_txn_date: date,
      p_raw_amount: amount,
      p_description: value(row, 'Description') || value(row, 'Name') || null,
      p_category: value(row, 'Category') || null,
    })
    if (error) return { ok: false, message: error.message }
    if (data) matched += 1
    else unmatched += 1
  }

  revalidatePath('/cash')
  return { ok: true, matched, unmatched, unreadable }
}

const reconcileSchema = z.object({
  recDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, 'a reconciliation belongs to a date'),
  cashAccountCode: z.string().min(1),
  /** What the US team's own book says the account closed at. */
  usClosing: z.number().refine(Number.isFinite, 'that is not a number'),
  status: z.enum(['PENDING', 'MATCHED', 'DIFF_EXPLAINED', 'NOT_FOUND']),
  reason: z.string().trim().max(500).nullable().optional(),
})

export type ReconcileResult = { ok: true; difference: number } | { ok: false; message: string }

/**
 * Records one account against what the other book says.
 *
 * Our closing figure is not taken from the form: it is read from the ledger at
 * the moment of reconciling. A reconciliation where both sides are typed proves
 * only that somebody can type, and the source's own sheet has that weakness.
 *
 * The difference is generated by the database from the two, so it cannot be
 * typed either. Calling one explained without an explanation is refused there
 * too — that constraint is the point of the column.
 */
export async function reconcileAccount(input: unknown): Promise<ReconcileResult> {
  const parsed = reconcileSchema.safeParse(input)
  if (!parsed.success) {
    return { ok: false, message: parsed.error.issues[0]?.message ?? 'Invalid reconciliation' }
  }
  const { recDate, cashAccountCode, usClosing, status, reason } = parsed.data
  const supabase = await createServerSupabase()

  const { data: ours, error: balanceError } = await supabase.rpc('cash_balance', {
    p_account: cashAccountCode, p_as_of: recDate,
  })
  if (balanceError) return { ok: false, message: balanceError.message }
  const ourClosing = Number(ours ?? 0)

  const { data: user } = await supabase.auth.getUser()
  const resolved = status === 'PENDING' ? null : new Date().toISOString()

  const { error } = await supabase.from('cash_reconciliation').upsert({
    rec_date: recDate,
    cash_account_code: cashAccountCode,
    our_closing: ourClosing,
    us_closing: usClosing,
    status,
    reason: reason ?? null,
    resolved_by: resolved ? (user.user?.id ?? null) : null,
    resolved_at: resolved,
  }, { onConflict: 'rec_date,cash_account_code' })
  if (error) return { ok: false, message: error.message }

  revalidatePath('/cash')
  return { ok: true, difference: Math.round((ourClosing - usClosing) * 100) / 100 }
}

const loanSchema = z.object({
  loanDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/),
  counterparty: z.string().trim().min(1, 'who was it lent to, or repaid by?'),
  direction: z.enum(['LEND', 'REPAY']),
  amount: z.number().positive('an amount of nothing is not a loan'),
  description: z.string().trim().max(300).nullable().optional(),
  approvedBy: z.string().trim().max(120).nullable().optional(),
})

export type LoanResult = { ok: true } | { ok: false; message: string }

/**
 * Records money lent between the group's own entities, or paid back.
 *
 * These sit on 1388 in the source and are the reason that account has an
 * opening balance with no credit side anybody could name. Keeping them as their
 * own list means the balance per counterparty is derivable rather than
 * remembered.
 */
export async function recordInternalLoan(input: unknown): Promise<LoanResult> {
  const parsed = loanSchema.safeParse(input)
  if (!parsed.success) {
    return { ok: false, message: parsed.error.issues[0]?.message ?? 'Invalid entry' }
  }
  const supabase = await createServerSupabase()
  const { error } = await supabase.from('internal_loan').insert({
    loan_date: parsed.data.loanDate,
    counterparty: parsed.data.counterparty,
    direction: parsed.data.direction,
    amount: parsed.data.amount,
    description: parsed.data.description ?? null,
    approved_by: parsed.data.approvedBy ?? null,
  })
  if (error) return { ok: false, message: error.message }

  revalidatePath('/cash')
  return { ok: true }
}
