// Writes the Ant Design stylesheet the app loads in zero-runtime mode.
//
//   npm run antd:css      (after upgrading antd, or changing the theme or its tokens)
//
// With zeroRuntime on (providers.tsx), antd stops writing each component's CSS
// while it renders. Measured on 15-09, that writing cost every server render of
// the ledger about a hundred milliseconds and put some 370 KB of CSS into every
// page. The styles come from here instead: every component, extracted by antd's
// own tool with the app's theme exactly as the providers set it, for the light
// theme and the dark one, into one file under public/antd/ whose name carries
// the antd version and a hash of the content, so browsers can keep it for good.
//
// antd's shipped dist/antd.css cannot stand in for this. Its variables sit under
// classes of its own and hold antd's default theme; tried on 15-09, tables lost
// their cell padding, selects their background and the dark menu its colours.
//
// `--check` prints what would be written, without writing it; the test in
// tests/lib/antd-stylesheet.test.ts uses it to catch a stylesheet left behind.
import { createHash } from 'node:crypto'
import { mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { antdThemeTokens } from '../src/lib/design/tokens.ts'
import { antdThemeConfig } from '../src/lib/design/antdTheme.ts'

const require = createRequire(import.meta.url)
const React = require('react')
const antd = require('antd')
const { extractStyle } = require('@ant-design/static-style-extract')

/** The top-level blocks of a stylesheet, found by balancing braces. */
function blocks(css) {
  const out = []
  let i = 0
  while (i < css.length) {
    const open = css.indexOf('{', i)
    if (open < 0) break
    let depth = 1
    let j = open + 1
    while (j < css.length && depth > 0) {
      if (css[j] === '{') depth += 1
      else if (css[j] === '}') depth -= 1
      j += 1
    }
    out.push(css.slice(i, j).trim())
    i = j
  }
  return out
}

/** The providers' wrapper for one theme, as the extractor wants it. */
function themed(theme) {
  return function WithTheme(node) {
    return React.createElement(antd.ConfigProvider, {
      theme: {
        algorithm: theme === 'dark' ? antd.theme.darkAlgorithm : antd.theme.defaultAlgorithm,
        ...antdThemeConfig(theme, antdThemeTokens(theme)),
      },
    }, React.createElement(antd.App, null, node))
  }
}

// The extractor renders some components inside a ConfigProvider of its own,
// whose variables land under a generated class (.css-var-_R_…). No element in
// the app carries those classes, so their blocks are left out.
const ours = (block) => !block.startsWith('.css-var-_R')

const version = JSON.parse(readFileSync(require.resolve('antd/package.json'), 'utf8')).version
const light = blocks(extractStyle(themed('light'))).filter(ours)
const inLight = new Set(light)
// Component rules come out the same for both themes; what differs is the
// variable blocks, and those are keyed by theme (pc-light, pc-dark). So the dark
// theme adds its own blocks after the light file without overriding any of it.
const darkOnly = blocks(extractStyle(themed('dark'))).filter(ours).filter((b) => !inLight.has(b))
const css = light.join('') + darkOnly.join('')
const hash = createHash('sha256').update(css).digest('hex').slice(0, 12)
const name = `antd-${version}-${hash}.css`
const href = `/antd/${name}`

if (process.argv.includes('--check')) {
  console.log(JSON.stringify({ href, bytes: css.length }))
} else {
  mkdirSync('public/antd', { recursive: true })
  for (const old of readdirSync('public/antd')) if (old !== name) rmSync(`public/antd/${old}`)
  writeFileSync(`public/antd/${name}`, css)
  writeFileSync('src/lib/design/antdStylesheet.ts',
    `// Generated by npm run antd:css; do not edit.\nexport const ANTD_STYLESHEET = '${href}'\n`)
  console.log(`antd@${version}: ${Math.round(css.length / 1024)} KB, ${light.length + darkOnly.length} blocks -> public${href}`)
}
