'use client'

import { useState, useTransition } from 'react'
import { useRouter } from 'next/navigation'
import { useLocale } from '@/lib/i18n/provider'
import { addLotLine, advanceLot, createLot } from '@/app/(app)/refining/actions'
import styles from './Refining.module.css'

export type GoldOption = { code: string; nameVi: string; nameEn: string }

/** Opening a lot. Two fields, because a draft holds nothing else yet. */
export function NewLot() {
  const { t } = useLocale()
  const router = useRouter()
  const [open, setOpen] = useState(false)
  const [code, setCode] = useState('')
  const [refinery, setRefinery] = useState('')
  const [error, setError] = useState<string | null>(null)
  const [pending, startTransition] = useTransition()

  function submit() {
    setError(null)
    startTransition(async () => {
      const result = await createLot({ lotCode: code, refineryName: refinery || null })
      if (!result.ok) { setError(result.message); return }
      setOpen(false); setCode(''); setRefinery('')
      router.refresh()
    })
  }

  if (!open) {
    return (
      <button type="button" className={styles.quiet} onClick={() => setOpen(true)}>
        {t('refining.newLot')}
      </button>
    )
  }

  return (
    <span className={styles.receive}>
      <input
        className={styles.field}
        aria-label={t('refining.lotCode')}
        placeholder={t('refining.lotCode')}
        value={code}
        onChange={(e) => setCode(e.target.value)}
      />
      <input
        className={styles.field}
        aria-label={t('refining.refinery')}
        placeholder={t('refining.refinery')}
        value={refinery}
        onChange={(e) => setRefinery(e.target.value)}
      />
      <button type="button" className={styles.quiet} disabled={pending} onClick={submit}>
        {t('refining.save')}
      </button>
      <button type="button" className={styles.quiet} disabled={pending}
              onClick={() => { setOpen(false); setError(null) }}>
        {t('refining.cancel')}
      </button>
      {error && <span className={styles.failed}>{error}</span>}
    </span>
  )
}

/**
 * Adding what went into a shipment.
 *
 * The owner is on the line rather than the lot: a shipment is pooled, so PC49's
 * metal and a partner's travel together and come back separately.
 */
export function AddLine({ lotId, goldTypes }: { lotId: string; goldTypes: GoldOption[] }) {
  const { locale, t } = useLocale()
  const router = useRouter()
  const [open, setOpen] = useState(false)
  const [owner, setOwner] = useState('PC49')
  const [gold, setGold] = useState(goldTypes[0]?.code ?? '')
  const [gross, setGross] = useState('')
  const [pct, setPct] = useState('')
  const [desc, setDesc] = useState('')
  const [error, setError] = useState<string | null>(null)
  const [pending, startTransition] = useTransition()

  function submit() {
    setError(null)
    startTransition(async () => {
      const result = await addLotLine({
        lotId,
        ownerCode: owner,
        goldTypeCode: gold,
        sourceDesc: desc || null,
        grossWeightGram: Number(gross),
        goldPct: Number(pct),
      })
      if (!result.ok) { setError(result.message); return }
      setGross(''); setPct(''); setDesc('')
      router.refresh()
    })
  }

  if (!open) {
    return (
      <button type="button" className={styles.quiet} onClick={() => setOpen(true)}>
        {t('refining.addLine')}
      </button>
    )
  }

  return (
    <span className={styles.receive}>
      <input className={`${styles.field} ${styles.owner}`} aria-label={t('refining.owner')}
             placeholder={t('refining.owner')} value={owner}
             onChange={(e) => setOwner(e.target.value)} />
      <select className={styles.field} aria-label={t('inv.goldType')} value={gold}
              onChange={(e) => setGold(e.target.value)}>
        {goldTypes.map((g) => (
          <option key={g.code} value={g.code}>{locale === 'vi' ? g.nameVi : g.nameEn}</option>
        ))}
      </select>
      <input className={`${styles.field} ${styles.qty}`} inputMode="decimal"
             aria-label={t('refining.gross')} placeholder={t('refining.gross')}
             value={gross} onChange={(e) => setGross(e.target.value)} />
      {/* A fraction, not a percentage: 0.75 rather than 75. The pure weight is
          generated by multiplying, so the wrong one is a hundredfold error. */}
      <input className={`${styles.field} ${styles.qty}`} inputMode="decimal"
             aria-label={t('refining.purity')} placeholder="0.75"
             value={pct} onChange={(e) => setPct(e.target.value)} />
      <input className={styles.field} aria-label={t('refining.sourceDesc')}
             placeholder={t('refining.sourceDesc')} value={desc}
             onChange={(e) => setDesc(e.target.value)} />
      <button type="button" className={styles.quiet} disabled={pending} onClick={submit}>
        {t('refining.save')}
      </button>
      <button type="button" className={styles.quiet} disabled={pending}
              onClick={() => { setOpen(false); setError(null) }}>
        {t('refining.cancel')}
      </button>
      {error && <span className={styles.failed}>{error}</span>}
    </span>
  )
}

/**
 * Moving a lot on one stage.
 *
 * Only the next stage is ever offered, because the cycle runs one at a time and
 * a control that would be refused is a control that should not be there.
 * RECEIVED is absent on purpose: it is not a decision somebody makes, it is
 * what recording the first receipt does.
 */
export function AdvanceLot({ lotId, status }: { lotId: string; status: string }) {
  const { t } = useLocale()
  const router = useRouter()
  const next = status === 'DRAFT' ? 'SENT'
    : status === 'SENT' ? 'ASSAYED'
      : status === 'RECEIVED' ? 'CLOSED'
        : null

  const [open, setOpen] = useState(false)
  const [date, setDate] = useState(() => new Date().toISOString().slice(0, 10))
  const [spot, setSpot] = useState('')
  const [error, setError] = useState<string | null>(null)
  const [pending, startTransition] = useTransition()

  if (next === null) return null

  const needsDetail = next === 'SENT' || next === 'ASSAYED'

  function submit() {
    setError(null)
    startTransition(async () => {
      const result = await advanceLot({
        lotId,
        to: next as 'SENT' | 'ASSAYED' | 'CLOSED',
        date: needsDetail ? date : null,
        spotGoldPerOz: needsDetail && spot ? Number(spot) : null,
      })
      if (!result.ok) { setError(result.message); return }
      setOpen(false)
      router.refresh()
    })
  }

  if (!open) {
    return (
      <button type="button" className={styles.quiet} onClick={() => setOpen(true)}>
        {t(`refining.to.${next}` as const)}
      </button>
    )
  }

  return (
    <span className={styles.receive}>
      {needsDetail && (
        <>
          <input type="date" className={styles.field} aria-label={t('refining.onDate')}
                 value={date} onChange={(e) => setDate(e.target.value)} />
          <input className={`${styles.field} ${styles.qty}`} inputMode="decimal"
                 aria-label={t('refining.spot')} placeholder={t('refining.spot')}
                 value={spot} onChange={(e) => setSpot(e.target.value)} />
        </>
      )}
      <button type="button" className={styles.quiet} disabled={pending} onClick={submit}>
        {t(`refining.to.${next}` as const)}
      </button>
      <button type="button" className={styles.quiet} disabled={pending}
              onClick={() => { setOpen(false); setError(null) }}>
        {t('refining.cancel')}
      </button>
      {error && <span className={styles.failed}>{error}</span>}
    </span>
  )
}
